# Generated by Django 5.1.2 on 2024-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_spotifywrap_name_alter_spotifywrap_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='duo_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrap',
            name='theme',
            field=models.CharField(choices=[('halloween', 'Halloween'), ('christmas', 'Christmas'), ('none', 'None'), ('duo', 'Duo-Wrap')], max_length=20),
        ),
    ]
