# Generated by Django 5.1.2 on 2024-11-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_spotifywrap_duo_username_alter_spotifywrap_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_id',
        ),
    ]
